### PR TITLE
[DEV] - Update time

### PR DESCRIPTION
**Pull request by TomDonoghue**
This PR updates spiketools to default to and work with spike times in seconds.

Relates to #11 & #12

### CODE REVIEW

**Comment by TomDonoghue** [comment]
Hey @claire98han & @maestapereira - as I think I've mentioned to both of you, as an answer to the open question of which time unit to use as default (#11), the suggestion from NWB is to use seconds, and so that is the plan. 

This PR updates various things to work with seconds. The biggest change is probably updating the management of spike trains, to handle seconds, and allow for setting the sampling rate. I think there should no longer be any discrepancy between different functions expecting different units. 

Since this is a fairly big change (conceptually, if not really in code), could you both have a quick look through this and check that 1) it all makes sense to you, and seems to work, 2) that I haven't missed anything, and 3) whether you see any problems that this might introduce.

Thanks!

**Review by maestapereira — APPROVED** [review]
Looks great! 
The only change that may be useful is making `check_spike_time_unit` check for milliseconds instead of seconds.

**Review by claire98han — APPROVED** [review]
@TomDonoghue - This looks great! Similar concerns as Sandra mentioned, `check_spike_time_unit` in `checks.py` currently raises warnings for spikes in seconds. We might want to check for spikes in ms instead. 

Also, the comments in `test_check_spike_time_unit` in `test_checks.py` seem to be flipped (the intention is to pass for seconds, raise an error for ms, right?).

**Comment by TomDonoghue** [comment]
Hey @claire98han & @maestapereira - thanks for checking through things!

Originally, I  hadn't really figured out what to do with `check_spike_time_unit`. I also realized we are not actually using this function anywhere anyways - we never actually added it into usage.

For now, I've generalized `check_spike_time_unit` -> `infer_time_unit`, which will return an inferred time unit. Now, if we want to add a warning anywhere, we can add something like:
```
if infer_time_unit(spikes) == 'milliseconds':
    print('Oh No! Wrong time units!!')
```

Does this make sense to y'all? I also fixed a couple other examples, and and updated `convert_train_to_times` to generalize to different sampling rates. From my end, I think this is ready to merge.

**Review by claire98han — COMMENTED** [review]
Hey @TomDonoghue - this totally makes sense! And also it might be easier this way even if we change our minds to use milliseconds later on. I think it's in a good shape to be merged!

**Pull request merged**
